language: python

install:
  - pip install -r requirements.txt

script:
  - pytest
  - mypy pyteal
  - black --check .

jobs:
  include:
    - stage: Testing
      name: Python 3.6
      python: "3.6"
    - name: Python 3.7
      python: "3.7"
    - name: Python 3.8
      python: "3.8"
    - name: Python 3.9
      python: "3.9"
    - stage: Release
      name: PyPi release
      python: "3.9"
      script: skip
      if: tag IS present AND type = push
      deploy:
        provider: pypi
        username: __token__
        on:
          tags: true
          branch: master
        distributions: "sdist bdist_wheel"
